name: Extension Code Quality
on:
  pull_request:
    paths-ignore: ["**.md"]
  push:
    paths-ignore: ["**.md"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Code Quality
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@72e76e99cd7fee45a99739cd118ec2db64e034ec
    with:
      extension_name: lance
      duckdb_version: 6367663157416c79e64875d96156d80059f2dc07
      ci_tools_version: 72e76e99cd7fee45a99739cd118ec2db64e034ec
